source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/itomych/dashdevsnetworking.git'

use_frameworks!

target 'ScannerFramework_Tests' do
  pod 'ScannerFramework', :path => '../'
  
  
end
